### ISSUE TITLE
Can't Start jar file

### ISSUE THREAD

**Issue by Villager1** [Kideneb/MinecraftMacroTool#4]
Exception in thread "main" java.lang.NumberFormatException: For input string: "key.mouse.left"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at logic.Config.readConfig(Config.java:183)
	at logic.Main.main(Main.java:31)
Happens every time I open the jar

**Comment by Kideneb** [comment]
This happens, because Mojang changed the format of the options.txt file.
I will fix it but I probably won't get around to it until the end of the month.

A workaround for this is:

- Open an older version of Minecraft (like 1.8.x).
-Change some key in the controls settings, save it.
-Change it back.
-Now open 1.16. The tool should work now.

**It will stop working however, once you change one of the control-settings on 1.16**

**Comment by Dojando1** [comment]
Hello, any chance for an update yet? :)
Just found the tool but can not get it to work because of the same issue. The workaround does not work anymore either unfortunately.
I would appreciate it.
Thank you ♥
