### ISSUE TITLE
Exception in thread "main" java.lang.NumberFormatException: For input string: "key.mouse.left"

### ISSUE THREAD

**Issue by Anachin2** [Kideneb/MinecraftMacroTool#8]
I put all 3 files in the directory, set up the config, and when I ran the jar file it reads
Exception in thread "main" java.lang.NumberFormatException: For input string: "key.mouse.left"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:665)
	at java.base/java.lang.Integer.parseInt(Integer.java:781)
	at logic.Config.readConfig(Config.java:183)
	at logic.Main.main(Main.java:31)

What do I do?

**Comment by Anachin2** [comment]
sorry, just read the other comment with this exact issue.
